"""Changed schema

Revision ID: 9c0918b48792
Revises: 5febdceefa58
Create Date: 2024-11-04 23:51:35.341233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0918b48792'
down_revision = '5febdceefa58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embed_code', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream', schema=None) as batch_op:
        batch_op.drop_column('embed_code')

    # ### end Alembic commands ###
