"""Changed schema

Revision ID: ccbed12a563d
Revises: 44f0afc727e8
Create Date: 2024-11-04 19:18:34.505950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccbed12a563d'
down_revision = '44f0afc727e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cam_angle', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('cam_label', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('stream_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('user_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.alter_column('object_id',
               existing_type=sa.INTEGER(),
               type_=sa.LargeBinary(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream', schema=None) as batch_op:
        batch_op.alter_column('object_id',
               existing_type=sa.LargeBinary(length=16),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('active')
        batch_op.drop_column('user_name')
        batch_op.drop_column('password')
        batch_op.drop_column('stream_name')
        batch_op.drop_column('cam_label')
        batch_op.drop_column('cam_angle')

    # ### end Alembic commands ###
