"""Changed schema

Revision ID: cef8f20baed9
Revises: 9c0918b48792
Create Date: 2024-11-05 00:16:02.583735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef8f20baed9'
down_revision = '9c0918b48792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stream_id', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream', schema=None) as batch_op:
        batch_op.drop_column('stream_id')

    # ### end Alembic commands ###
